# Generated by Django 3.2.6 on 2021-12-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'price']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
